# Site settings
title: "rlShaders"
description: "Physically-based shading experiments in Arnold renderer."
twitter_username: shihchinw
github_username:  shihchinw

# Handling Reading
exclude:      ["less","node_modules","Gruntfile.js","package.json","README.md"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
whitelist: []
# gems: [jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:      /:year/:month/:title.html
# paginate:       5
# paginate_path:  /page:num
timezone:       Asia/Taipei

# Markdown Processors
kramdown:
    input: GFM
    auto_ids: true

pages_list:
    Install: "/pages/install"
    References: "/pages/references"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Shih-Chin"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
